package com.app.dream11.newhome.navigation;
/* loaded from: classes3.dex */
public enum NavItem {
    INVITE_FRIEND,
    INVITE_FRIEND_MENU,
    SEASON_LONG_BANNER,
    PROFILE_AVATAR_CHANGE,
    PROFILE_HEADER_CONTAINER,
    HEADER_APP_UPDATE,
    MY_BALANCE_MENU,
    MY_BALANCE_ADD_CASH,
    FC_MERCHANDISE_PUMA,
    FC_MERCHANDISE_FAN,
    APP_UPDATE,
    FIND_PEOPLE_MENU,
    TIER_MENU,
    MY_REWARDS_MENU,
    HOW_TO_PLAY_MENU,
    FANCODE_MENU,
    FANCODE_SHOP_MENU,
    FANCODE_MERCHANDISE_MENU,
    MY_INFO_SETTINGS_MENU,
    MORE_MENU,
    FEATURE_DASHBOARD_MENU,
    VERSION_UPDATE_MENU,
    HEADER,
    DIVIDER
}
