package com.appsamurai.storyly.analytics;
/* loaded from: classes3.dex */
public enum StorylyEvent {
    StoryGroupOpened,
    StoryGroupUserOpened,
    StoryGroupDeepLinkOpened,
    StoryGroupProgrammaticallyOpened,
    StoryGroupCompleted,
    StoryGroupPreviousSwiped,
    StoryGroupNextSwiped,
    StoryGroupClosed,
    StoryImpression,
    StoryViewed,
    StoryCompleted,
    StoryPreviousClicked,
    StoryNextClicked,
    StoryPaused,
    StoryResumed,
    StoryShared,
    StoryCTAClicked,
    StoryEmojiClicked,
    StoryPollAnswered,
    StoryQuizAnswered,
    StoryCountdownReminderAdded,
    StoryCountdownReminderRemoved,
    StoryRated,
    StoryInteractiveImpression,
    StoryProductTagExpanded,
    StoryProductTagClicked,
    StoryPromoCodeCopied,
    StoryCommentSent,
    StoryCommentInputOpened,
    StoryCommentInputClosed,
    StoryIVodSeeked,
    StoryIVodReplayed,
    StoryLiked,
    StoryUnliked
}
